 - name: Build Angular App
      working-directory: digital-banking-platform/transaction-ui/transaction-ui
      run: |
        npm install
        npm run build

    - name: Build Spring Boot App
      working-directory: digital-banking-platform/backend
      run: mvn clean package

    - name: Run Backend Tests
      working-directory: digital-banking-platform/backend
      run: mvn test
